name: Reusable Deploy Pipeline workflow 

# Declare as reusable workflow
# by only making it trigger when called through another workflow
# i.e Main.yml parent pipeline
on:
  workflow_call

# Declare pipeline environment variables
env:
    AZURE_WEBAPP_NAME: wa-dev-eastus-tfstate    # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '20.x'                # set this to the node version to use 

permissions:
    contents: read
  
# Declare deploy job steps and Github Actions ubuntu runner
# on Dev environment
jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    # Use the Service Principle you configured earlier to login to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_LOGIN_SP }}

    # Deploy web app job
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
