name: Deploy Pipeline

# Declare as reusable workflow
# by only making it trigger when called through another workflow
# i.e Main.yml parent pipeline
on:
    workflow_call

permissions:
    contents: read